# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-testing-parse:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements_test.txt; fi
    - name: Parsing Testing
      run: |
        pytest -vv test_parse.py -n 2
    - name: Query Testing
      run: |
        cd test && sh ./get_data.sh
        cd ..
        pytest --capture=tee-sys -vv test.py -n 2
        pytest --capture=tee-sys -vv test_extraction.py -n 2
        pytest --capture=tee-sys -vv test_visualize.py -n 2
        pytest --capture=tee-sys -vv test_translate.py -n 2
        pytest --capture=tee-sys -vv test_file_loading.py
        
